# Generated by Django 4.0.1 on 2022-01-30 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mit', models.CharField(db_index=True, max_length=255, verbose_name='Mit')),
                ('color', models.CharField(max_length=60, verbose_name='Color')),
                ('mod', models.CharField(max_length=200, verbose_name='Model')),
                ('car_type', models.IntegerField(choices=[(1, 'хэтчбек'), (2, 'Универсал'), (3, 'Седан'), (4, 'Внедорожник')], verbose_name='Car_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
